### ISSUE TITLE
Никто не гарантирует что в file_path будет > 1 элемента.  и переименевывать стандартные параметры main не принято

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikSavilov/WB-converter#1]
https://github.com/NikSavilov/WB-converter/blob/76a7e03200d48ae576470becfc3170aa22c00108/main.c#L112

**Comment by NikSavilov** [comment]
Добавил условия по количеству аргументов.
Стандартные параметры main, я так понял, это argc и argv?

**Comment by ahvastunov-itmo** [comment]
Да
