### ISSUE TITLE
Велосипед не изчез, не понятно зачем запоминать номер в параметрах. Проще сразу по месту скопировать нужное. 

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikSavilov/WB-converter#17]
https://github.com/NikSavilov/WB-converter/blob/8fa324a6e72e257ea4fe378dde40cc6db135b12b/main.c#L11

**Comment by NikSavilov** [comment]
Велосипед не случаен. Во-первых, выдерживается логическая последовательность действий. Сначала работаем с ключами, а потом на основе полученной информации выбираем режим работы.
Во-вторых, порядок ключей заранее неизвестен. Если память буду выделять в цикле, то могу встретиться с некоторыми неприятностями.
-om -i=<path>                        не сможет выделить память, т.к. длина пути еще неизвестна
-i=<path> -o=<path> -om    зазря выделит память в цикле, т.к. -om и -o= несовместимы
